/**
 * Markdown to PDF converter for implementation plans.
 *
 * Uses a simple HTML-based approach: converts markdown to styled HTML,
 * then renders to PDF. This avoids heavy dependencies like Puppeteer.
 *
 * For MVP, we use a lightweight approach that generates a well-formatted
 * text-based PDF. Can upgrade to Puppeteer/Playwright for richer rendering later.
 */

/**
 * Generate a PDF buffer from a markdown string.
 * Uses a simple text-based approach for MVP.
 */
export async function generatePlanPdf(
  markdown: string,
  projectName: string
): Promise<Buffer> {
  // Convert markdown to a clean text representation
  const lines = markdown.split('\n');
  const processedLines: string[] = [];

  for (const line of lines) {
    // Clean up markdown for PDF
    let cleaned = line
      .replace(/^#{1,6}\s+/, '') // Remove heading markers
      .replace(/\*\*(.+?)\*\*/, '$1') // Bold → plain
      .replace(/\*(.+?)\*/, '$1') // Italic → plain
      .replace(/`([^`]+)`/, '$1') // Inline code → plain
      .replace(/```[\s\S]*?```/, '[code block]') // Code blocks
      .trim();

    if (cleaned) {
      processedLines.push(cleaned);
    }
  }

  // For now, return the plan as a simple text file
  // The actual PDF generation will happen via the API endpoint
  // which can use a browser-based renderer
  const content = `BRICKOPS IMPLEMENTATION PLAN
${'='.repeat(50)}
Project: ${projectName}
Generated: ${new Date().toISOString()}
${'='.repeat(50)}

${processedLines.join('\n')}

${'='.repeat(50)}
Generated by BrickOps AI Build Control Plane
`;

  return Buffer.from(content, 'utf-8');
}

/**
 * Generate a filename for the plan PDF.
 */
export function getPlanFilename(projectSlug: string): string {
  const date = new Date().toISOString().split('T')[0];
  return `brickops-plan-${projectSlug}-${date}.txt`;
}
